### ISSUE TITLE
Notebook demonstrating eight schools model

### ISSUE THREAD

**Issue by sharanry** [pymc-devs/pymc4#10]
[Notebook](https://gist.github.com/sharanry/f44e874074b6cc5edbd613762cfe1ea5) demonstrating eight schools model

@ColCarroll @ferrine @junpenglao

**Comment by fonnesbeck** [comment]
Is this an issue?

Really nice start. I can see the `cfg` business being a point of confusion. Can it be replaced by `model` attributes, perhaps?

**Comment by sharanry** [comment]
@fonnesbeck The attributes defined while initializing the model are accessed using `cfg`.

**Comment by sharanry** [comment]
@ColCarroll Here is the notebook trying to compare pymc3 implementation of centered eight schools with pymc4 results. I feel I am going wrong some where as I am getting totally different results.

**Comment by sharanry** [comment]
Final [Notebook](https://gist.github.com/sharanry/193f06f139ccf1b90e176139238a4468) comparing the results.
