### ISSUE TITLE
Mutable update

### ISSUE THREAD

**Issue by ferrine** [pymc-devs/pymc4#108]
https://github.com/pymc-devs/pymc4/blob/a5523877ceea1c695051987d2a7c3ad9e1c78d9b/pymc4/_model.py#L103

Minimal example

```
import copy
class My(object):
    def __init__(self):
        self.mutable = dict()
my1 = My()
my2 = copy.copy(my1)
my2.mutable.update(a=1)
print(my1.mutable)
```

**Comment by lucianopaz** [comment]
Closing as this seems to be something relevant for the old context based API
