### ISSUE TITLE
Store Dictionary of Vars in Forward and Inference Context rather than list

### ISSUE THREAD

**Issue by canyon289** [pymc-devs/pymc4#112]
Change this to a dictionary to allow for ease of debugging and stronger ability to check that all variables are passed to `log_prob` function

https://github.com/pymc-devs/pymc4/blob/master/pymc4/_template_contexts.py#L47

**Comment by canyon289** [comment]
Talking to @fonnesbeck may not be needed since RVs store their name as an attribute. Leaving issue open for now though until we have a more in depth discussion

**Comment by lucianopaz** [comment]
Closing as this applied to the old api
