### ISSUE TITLE
auto_name doesn't work if a line contains more than just the RV specifciation

### ISSUE THREAD

**Issue by ericmjl** [pymc-devs/pymc4#122]
Model:

```python
@pm.model(auto_name=True)
def model():
    ....
    # The offending line is this one.
    nu = pm.Exponential(lam=1 / 29.0) + 1
    ...
```

Error message:

```
________________________________________________________________________ ERROR collecting pymc4/tests/test_hierarchical_comparison.py ________________________________________________________________________
pymc4/tests/test_hierarchical_comparison.py:41: in <module>
    model = model.configure()
pymc4/_model.py:64: in configure
    model._evaluate()
pymc4/_model.py:80: in _evaluate
    self._template._func(*args, **kwargs)
pymc4/tests/test_hierarchical_comparison.py:33: in model
    nu = pm.Exponential(lam=1 / 29.0) + 1
pymc4/random_variables/random_variable.py:134: in __init__
    raise ValueError("No name was set. Supply one via the name kwarg.")
E   ValueError: No name was set. Supply one via the name kwarg.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=================================================================================== 52 deselected, 1 error in 1.79 seconds ===================================================================================
```

**Comment by twiecki** [comment]
What is the error message you got?

**Comment by ericmjl** [comment]
Updated with error message.

**Comment by twiecki** [comment]
Actually this is OK, we *could* add this as a special case to the AST parsing but it's not meant to support every case and the error message is informative.

**Comment by eigenfoo** [comment]
@twiecki do we have a plan for auto-naming? From @ericmjl's snippet it looks like we're going for an `auto_name` flag that uses the AST to parse (nice!). If that's, I can spend some cycles and powow on this issue.

I'm a bit confused at how the `auto_name` flag works, though: I don't actually see it in the codebase anywhere, except in example notebooks. Which `.py` file is the relevant one?

**Comment by twiecki** [comment]
@eigenfoo That'd be great! Here is the code that walks the AST: https://github.com/pymc-devs/pymc4/blob/rugby_example/pymc4/ast_compiler.py#L117 and here is where it's used: https://github.com/pymc-devs/pymc4/blob/rugby_example/pymc4/_model.py#L30

Note that I think we should do things differently than I had originally implemented. I parsed and *changed* the AST to insert the name kwarg into the code. This has several downsides, one of them is that it's brittle and also that it doesn't work with `@function` compilation. Instead, it would be much simpler to just parse the AST to identify all yields, retrieve the rhs var names and store them in a list. Then when we do the interception in control-flow we change the default RV names to those from the stored list. Obviously this doesn't allow for dynamic graphs but that's a fine limitation. Some care needs to be taken care with model nesting but I think if we have that logic in the `@model` decorator we should be able to get a clean implementation.
