### ISSUE TITLE
Error is not captured for models with no free RVs

### ISSUE THREAD

**Issue by rrkarim** [pymc-devs/pymc4#170]
There is no exception handling for models with only observed variables. Maybe one can add `ndim` method to the state object to make all the checks in `sample` method but there is some ambiguity with shape support #91? How to better fix the issue?

**Comment by lucianopaz** [comment]
Would you like `inference.sampling.sample` to raise an error under these circumstances? It should be easy to do in `build_model_logp*`. Would you like to try a PR?

**Comment by rrkarim** [comment]
Yeah, sure, I thought that it might be clear if all the checking is done in `sample` method..
