### ISSUE TITLE
Observed dict passed in `sample` does not really make RVs observed

### ISSUE THREAD

**Issue by rrkarim** [pymc-devs/pymc4#177]
Maybe I don't know the real purpose of `observed` param in `sample` method, but executors do not care about these dicts and transform the distribution even if you provide new observed values. Is it intentional logic?

**Comment by rrkarim** [comment]
The problem I guess that there is not scoping when you pass it through the dict and in `proceed_distribution` (line 542) it doesn't see it as observed.

**Comment by lucianopaz** [comment]
The executors do care about the `observed` dict. It's tested in the context of forward sampling. [Here's the fixture](https://github.com/pymc-devs/pymc4/blob/master/tests/test_forward_sampling.py#L41-L69) that defines the model and [here is the test](https://github.com/pymc-devs/pymc4/blob/master/tests/test_forward_sampling.py#L154-L174). Maybe you could write a test case for `sample` to make sure it works?

**Comment by lucianopaz** [comment]
[here's](https://github.com/pymc-devs/pymc4/blob/master/pymc4/flow/executor.py#L625-L628) where we get the observed value from the state and [this is where we build the state from observed](https://github.com/pymc-devs/pymc4/blob/master/pymc4/flow/executor.py#L329-L330)

**Comment by rrkarim** [comment]
```
@pm.model
def model():
    mu = yield pm.Normal("mu", loc=0., scale=5)
    return mu

trace, sample_stat = pm.inference.sampling.sample(model(), 
                                                  num_samples=10, 
                                                  observed={"mu":1.})
```
This snippet should raise an exception.

**Comment by lucianopaz** [comment]
The problem is that you're not passing the correct name. It should be `model/mu` because of the scoping

**Comment by rrkarim** [comment]
I see that, thanks. I didn't know you need to pass the model name for the main scope. Sorry.
