### ISSUE TITLE
Smarter "test point"

### ISSUE THREAD

**Issue by ColCarroll** [pymc-devs/pymc4#186]
Currently, we draw a sample from the prior predictive distribution to initialize and query shapes of the compute graph. It would be nice to have a test point instead or additionally, which would enable improper priors (i.e., `pm.Flat` should not have a random method, but it _could_ have a `test_point` or similar).

**Comment by lucianopaz** [comment]
This is the same issue as #167. A test point would work, but we would need a new executor to do the forward pass

**Comment by ColCarroll** [comment]
Wow, pretty exactly the same. Thanks!
