### ISSUE TITLE
Sampled values not transformed back?

### ISSUE THREAD

**Issue by ericmjl** [pymc-devs/pymc4#192]
In the PyMC4 Made Simple notebook I wrote, I found that the `sig` parameter was not transformed back from unbounded space to positive support space in the trace. Instead, I had to access `model/__log_sig`. I think we need to implement an auto back-transform so that ArviZ plots the posterior distribution of `model/sig` rather than `model__log_sig`.

**Comment by ColCarroll** [comment]
Yah, #180 fixes it. I want to kick the tires a little more on it before merging.

**Comment by lucianopaz** [comment]
This is a duplicate from #169
