### ISSUE TITLE
Implement Mixture Distribution

### ISSUE THREAD

**Issue by lucianopaz** [pymc-devs/pymc4#197]
This is linked to #44. At the moment we don't have a working `Mixture` distribution. I'm opening this as a smaller (kinda-) begginer friendly issue. It should work on top of [`tfd.Mixture`](https://www.tensorflow.org/probability/api_docs/python/tfp/distributions/Mixture) but be able to take a list of pymc4 `Distribution`s (not values yielded from distributions!!) as its components.

**Comment by rrkarim** [comment]
There was an issue on tf side, tensorflow/probability#684, I've opened a PR for it but still waiting for some response on it.

**Comment by golanor** [comment]
Hi,

I'd like to work on this issue. From the thread on tfp it seems like the issue there is fixed.

**Comment by rrkarim** [comment]
@golanor the issue hasn't been solved yet, unfortunately. Here is the PR for it #209 and the discussion of the `tf` issue: tensorflow/tensorflow/issues/35099.

**Comment by TomKealy** [comment]
I would also like to work on this issue!

**Comment by as135** [comment]
I'm going to take a look at this and see what I can do!

**Comment by lucianopaz** [comment]
Closed by #284
