### ISSUE TITLE
Supported Python versions?

### ISSUE THREAD

**Issue by ColCarroll** [pymc-devs/pymc4#2]
I will suggest developing on 3.6, but will add Python 3.5 to travis for now.  I would love to hear if there are good reasons to make sure to keep supporting 3.5, since 3.7 is coming out so soon.

**Comment by leblancfg** [comment]
FWIW, Debian 9 (stable) uses Python 3.5, and has a projected end-of-life for August 2020.

**Comment by ColCarroll** [comment]
Ah, thanks for that info!  f-strings and variable type annotations are probably [the features that we lose](https://docs.python.org/3/whatsnew/3.6.html) by supporting Python 3.5, but I don't think that's _so_ onerous.  I do love f-strings though...

**Comment by junpenglao** [comment]
3.5 ignores the variable annotations right? so we can have them in the code anyway.

**Comment by twiecki** [comment]
Agreed, 3.6 should be fine and we should make use of all new features we have.

**Comment by ColCarroll** [comment]
Cool - I will update travis to start building on 3.6 and 3.7-dev!  Thanks for all the input!
