### ISSUE TITLE
`batch_shape` param for non scalar distributions

### ISSUE THREAD

**Issue by rrkarim** [pymc-devs/pymc4#210]
Is there a need for shape param in `pm.Distribution`? There is no support to change `batch_shape` of distribution on `tfp` side and as I've asked recently in [google-groups-tfp](https://groups.google.com/a/tensorflow.org/forum/#!topic/tfprobability/IlfxOrcku0E), it is suboptimal to change it out of construction, I'm not sure why though. Should it be added here or be discussed to be added on `tfp` side?

**Comment by junpenglao** [comment]
You can change batch_shape on tfp side by using `tfd.Independent` and `tfd.Sample`, but there are things you cannot do and that's the proposal in https://github.com/pymc-devs/pymc4/pull/193 by @lucianopaz So yes there is plan to add this support to pymc4 and potentially upstream to tfp.
