### ISSUE TITLE
FileNotFoundError during installation

### ISSUE THREAD

**Issue by Sayam753** [pymc-devs/pymc4#211]
Environment Specifications - 

- Pip version: 20.0.2

- Python version: python3.7.5

- OS details: Darwin My_MacBook 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64

```bash
pip install pymc4
Collecting pymc4
  Using cached pymc4-4.0a1.tar.gz (39 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/46/w95zfpbs4n74rpszpy07g0tr0000gn/T/pip-install-w76s9ibg/pymc4/setup.py'"'"'; __file__='"'"'/private/var/folders/46/w95zfpbs4n74rpszpy07g0tr0000gn/T/pip-install-w76s9ibg/pymc4/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/46/w95zfpbs4n74rpszpy07g0tr0000gn/T/pip-install-w76s9ibg/pymc4/pip-egg-info
         cwd: /private/var/folders/46/w95zfpbs4n74rpszpy07g0tr0000gn/T/pip-install-w76s9ibg/pymc4/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/46/w95zfpbs4n74rpszpy07g0tr0000gn/T/pip-install-w76s9ibg/pymc4/setup.py", line 65, in <module>
        install_requires=get_requirements(REQUIREMENTS_FILE),
      File "/private/var/folders/46/w95zfpbs4n74rpszpy07g0tr0000gn/T/pip-install-w76s9ibg/pymc4/setup.py", line 35, in get_requirements
        with codecs.open(path) as buff:
      File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/codecs.py", line 904, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/46/w95zfpbs4n74rpszpy07g0tr0000gn/T/pip-install-w76s9ibg/pymc4/requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
Can someone guide me how to fix this?

**Comment by lucianopaz** [comment]
That's weird, I'll take a look at whether the requirements files are bundled up in pypi. For now, to be able to install pymc4, you'll have to clone the repo from GitHub or just download the source code. Then, in a terminal, you'll have to cd into the folder where you placed pymc4's source code and run `pip install path/to/pymc4`. If you plan to work on contributions to pymc4, then you can run `pip install -e path/to/pymc4` instead.

**Comment by lucianopaz** [comment]
I checked out the pypi tarball and, in fact, the requirements.txt file isn't included there. It's strange because we do include them in the `Manifest.in` and because when I build the `sdist` and `bdist_wheel`'s locally, the requirements.txt is included.
We'll upload a new release candidate to PYPI, that will fix the problem you're seeing and will let you `pip install pymc4` without errors. To install pymc4 now you have two options:

1. `pip install git+https://github.com/pymc-devs/pymc4.git`
2. Download the source code manually to some folder (or clone/fork the repository) and then `pip install /path/to/pymc4/source` (you can optionally add the `-e` flag to make development easier.

**Comment by Sayam753** [comment]
@lucianopaz I am able to install pymc4 using these options. Thanks for helping me out!

**Comment by lucianopaz** [comment]
With the v4.0a2, this is now fixed
