### ISSUE TITLE
Add a test that samples from a Uniform

### ISSUE THREAD

**Issue by lucianopaz** [pymc-devs/pymc4#216]
Issue #214 was closed by #215. However, we still haven't added a test to the test suite that tries out the new default `_init_transform` that we impose in `UnitContinuosDistribution`.

We basically have to add a test where we `pm.sample` from a model that has a `Uniform` distribution, and check that the autotransformed is part of the trace.

**Comment by tirthasheshpatel** [comment]
I want to take this up!
Just a little confused, why does the state not have any transformed values even though `Sigmoid` transform is applied to `Uniform` distribution.
I used this code to generate the samples: 
```python
>>> import pymc4 as pm
>>> @pm.model
... def main_model():
...  x = yield pm.Uniform('x', 0, 1)
...  return x
...
>>> ret, state = pm.evaluate_model(main_model())
>>> state.untransformed_values
{'main_model/x': <tf.Tensor: shape=(), dtype=float32, numpy=0.7253169>}
>>> state.transformed_values
{}
>>> samples = pm.sample(new_model(), num_samples=10, burn_in=1)
>>> samples
Inference data with groups:
        > posterior
        > sample_stats
        > observed_data
```
I have two questions:
 - Why are there no transformed values (or are they just hidden)?
 - How to get the autotransformed values from `samples`?

**Comment by tirthasheshpatel** [comment]
Also, I wrote this test suite. I am getting it right? (clearly, the ``assert`` line has to be changed)
```python
def test_uniform_sample():
    @pm.model
    def model():
        dist = yield pm.Uniform('uniform', 0, 1)
        return dist
    
    trace = pm.sample(model(), num_samples=1, burn_in=1)

    assert samples.posterior['new_model/x_transformed'] is not None
```

**Comment by lucianopaz** [comment]
Great, @tirthasheshpatel! The reason you're not seeing the transformed values in the state is because you need to use a different executor. Instead of `evaluate_model` use `evaluate_model_transformed`.
About the test, yes that is very good. I would also test if the regular untransformed uniform distribution is present.

**Comment by tirthasheshpatel** [comment]
Thanks for the reply! But I think Uniform doesn't apply transform as it doesn't inherit `UnitContinousDistribution`.
```python
>>> state
SamplingState(
    untransformed_values: ['model/x']
    transformed_values: []
    observed_values: []
    distributions: ['Uniform:model/x']
    num_potentials=0
    deterministics: ['model']
    posterior_predictives: [])
```

So, I think this is what we need to do:
```python
class Uniform(UnitContinuousDistribution, BoundedContinuousDistribution):
    ...
```

I did that and the tests pass:
```python
>>> ret, state = pm.evaluate_model_transformed(model())
2020-02-05 09:27:52.141621: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
>>> state
SamplingState(
    untransformed_values: ['model/x']
    transformed_values: ['model/__sigmoid_x']
    observed_values: []
    distributions: ['Uniform:model/x']
    num_potentials=1
    deterministics: ['model']
    posterior_predictives: [])
```

**Comment by lucianopaz** [comment]
Oh, stupid me! Uniform is bounded but not necessarily between zero and one. We should do this test on the `Beta` distribution and leave the `Uniform` as it was.

**Comment by tirthasheshpatel** [comment]
Oh, It's fine! I changed the tests. Do we need tests for other UnitContinuousDistributions though?
