### ISSUE TITLE
Refactor/update BetaBinomial Distribution

### ISSUE THREAD

**Issue by junpenglao** [pymc-devs/pymc4#230]
Following https://github.com/tensorflow/probability/commit/bf79507598e025b707d39da82cc4fb49dec10d03, TFP now have a more efficient implementation of BetaBinomial

**Comment by junpenglao** [comment]
@tirthasheshpatel would you like to follow up on this?

**Comment by tirthasheshpatel** [comment]
@junpenglao  sure!
