### ISSUE TITLE
Code coverage reports of PRs fail to upload

### ISSUE THREAD

**Issue by lucianopaz** [pymc-devs/pymc4#232]
For some reason, our azure pipelines CI for pull requests fail to upload the coverage reports. I'll try to take a closer look later this week.

**Comment by OriolAbril** [comment]
Hi, it looks like it is related to [this issue](https://community.codecov.io/t/codecov-uploads-from-azure-pipelines-are-failing-with-build-numbers-do-not-match/1100?u=oriolabril) in ArviZ we are using [a workaround](https://community.codecov.io/t/codecov-uploads-from-azure-pipelines-are-failing-with-build-numbers-do-not-match/1100/13?u=oriolabril) until this is solved.

**Comment by lucianopaz** [comment]
Thanks @OriolAbril! The link was really helpful. We'll have to use the same workaround until codecov solves the problem on their end
