### ISSUE TITLE
Distributions do not validate argument

### ISSUE THREAD

**Issue by ritesh99rakesh** [pymc-devs/pymc4#236]
Many distributions do not validate arguments:
```python
>>> import pymc4
>>> x = pymc4.distributions.Normal('x', loc=0, scale=-2)
>>> x.sample()
<tf.Tensor: shape=(), dtype=float32, numpy=4.025787>
>>> x = pymc4.distributions.Uniform('x', low=0, high=-2)
>>> x.sample()
<tf.Tensor: shape=(), dtype=float32, numpy=-0.24736929>
```

One way to solve would be set `validate_args=True` in TensorFlow distribution calls:
```python
@staticmethod
def _init_distribution(conditions):
    loc, scale = conditions["loc"], conditions["scale"]
    return tfd.Normal(loc=loc, scale=scale, validate_args=True)
```
which would give the following error:
```python
 = pymc4.distributions.Normal('x', loc=0, scale=-2)
Traceback (most recent call last):
...
Condition x > 0 did not hold element-wise:
x (shape=() dtype=float32) = 
-2.0
```

If the community thinks that this is a valid issue then I can work on it.

**Comment by ericmjl** [comment]
I think this is a good idea. I’d be curious to know, however, whether the TFP error messages are informative for an end-user to know what they should change... afaik, the TF ecosystem of tools aren’t user-friendly that way. Can you post back what errors are raised if invalid values are passed in?
