### ISSUE TITLE
Using statistical functions in PyMC4

### ISSUE THREAD

**Issue by xiangze** [pymc-devs/pymc4#26]
pymc3.stats has functions to evaluate the models  such as Rhat, HPD, AIC,WAIC and LOO. 
How about  implement these function in PyMC4?

**Comment by ColCarroll** [comment]
Yes! once https://arviz-devs.github.io/arviz/ is a little more stable, the plan is to use `xarray` as the pymc4 data store, and arviz to do the plotting and diagnostics. All the calculations should already work, but there's quite a bit to be done to get xarray integrated more closely.
