### ISSUE TITLE
Simple OLS problem not working

### ISSUE THREAD

**Issue by sadatnfs** [pymc-devs/pymc4#27]
Hello:

I have mostly operated with TF and TFP in the past, and I thought it'd be a great time to give PyMC4 a try, given that all the HMC work will be easily implemented in the backend. However, it seems like I can't seem to make a simple OLS model run properly..

I have my model code here with all the outputs: https://gist.github.com/sadatnfs/d5004f488ba00371333770059ab99776
If you look at the traces printed, you'll see that all 3 parameters of the OLS model is staying at 0.5 (which I'm guessing is the initialized value by TF), whereas when I ran the eight schools example from the example as-is, it ran the sampling all good...

I feel like I'm missing something super simple and trivial... any thoughts?

Thanks!

**Comment by yukinagae** [comment]
Try using smaller `step_size` parameter:

```python
pymc4_trace = pm4.sample(pymc4_ols,  num_burnin_steps=1000, num_results=20, step_size=0.01)
```

The current default setting of `step_size` is 0.4 which might be too big for your model.

**Comment by sadatnfs** [comment]
you are absolutely correct! Thanks so much!
