### ISSUE TITLE
How can I customize the chain and core number like pymc3? 

### ISSUE THREAD

**Issue by handgunsoldier** [pymc-devs/pymc4#28]
In pymc3, I can use `pm.sample(5000, cores=4, tune=500, chains=4)`  explicitly to run with 4 chains and 4 CPU cores. But I find there are no such parameters in pymc4, `sample(model, num_results=5000, num_burnin_steps=3000, step_size=.4, num_leapfrog_steps=3, numpy=True)`. How can I make it?

Besides, since pymc4 builds upon TensorFlow, can I switch to GPU version manually when sampling?

Thanks!

**Comment by twiecki** [comment]
@handgunsoldier PyMC4 isn't really ready for users, just a prototype.
