### ISSUE TITLE
PyMC3 vs PyMC4 for a new project?

### ISSUE THREAD

**Issue by maresb** [pymc-devs/pymc4#300]
Greetings! I hope this is an appropriate place to ask this... I'm fairly new to Bayesian modelling, and I would like to use it for some real-world projects. On one hand I'm very impressed with the extensive PyMC3 documentation, but on the other hand having TFP as a backend seems so much more powerful.

I'm leaning towards starting with PyMC3 because of the pre-release disclaimer:
> Do not use for anything serious.

I have been watching PyMC4 for a while and have always seen a lot of activity, yet I'm unable to find any indication for whether the rough timescale for the first release version would be closer to a month or a year. If PyMC4 is on the verge of release, I'd much rather invest my time into learning that. I would be grateful for any advice. Thanks so much for your time!

**Comment by fonnesbeck** [comment]
Please post general questions to the [Discourse site](https://discourse.pymc.io/). The issues are for reporting bugs only. Thanks.

**Comment by maresb** [comment]
Sorry for the noise, and thanks so much for the Discourse reference! Just in case someone else stumbles across this, my question is more-or-less addressed here:
  https://discourse.pymc.io/t/is-pymc4-dead-or-just-resting/5330
