### ISSUE TITLE
Add support for LocalLinearTrend and Seasonal

### ISSUE THREAD

**Issue by kori73** [pymc-devs/pymc4#322]
I would like to work on adding a few time-series distributions starting with LocalLinearTrend and Seasonal.

Looking at the discussions for the [AR pull request](https://github.com/pymc-devs/pymc4/pull/220), I see that you are not currently happy with the way the `initial_state_prior` for tfp is obtained. Currently, we are passing a MultivariateNormalDiag with `initial_state` mean and std close to 0.

I have checked how the `initial_state_prior` is used in the base class (`LinearGaussianStateSpaceModel`) and it seems that the `covariance` method needs to be implemented.

Do you have any suggestions on how to proceed?

**Comment by fonnesbeck** [comment]
@kori73 Thanks for your interest. The development team [has made the decision not to continue with the TFP-based version of PyMC](https://pymc-devs.medium.com/the-future-of-pymc3-or-theano-is-dead-long-live-theano-d8005f8a0e9b). We will instead be updating the Theano backend to make it compile with JAX and other engines. If you are interested in contributing to PyMC, I'd suggest directing your attention to the PyMC3 repo, as it will continue to the main supported version of PyMC.
