### ISSUE TITLE
Port the usage of already impelemnted HMC sampling in tfp

### ISSUE THREAD

**Issue by sharanry** [pymc-devs/pymc4#4]
[Link](https://github.com/tensorflow/probability/blob/master/tensorflow_probability/python/mcmc/hmc.py) to implementation

**Comment by sharanry** [comment]
[Notebook](https://gist.github.com/sharanry/6b6439d81b4b0e18a46b52ed542a8387) demonstrating the use of HMC. PR will be made soon.

**Comment by junpenglao** [comment]
Judging from the merge message, pretty sure they are deprecating the tf contrib distribution: https://github.com/tensorflow/probability/commit/0714da045f8bac5ecbcb7b84f20e743088c1c6a5

They probably already done so in the nightly release - we should pin the version up in the config in both branches.
