### ISSUE TITLE
[Question] Where is object ArrayStep defined?

### ISSUE THREAD

**Issue by canyon289** [pymc-devs/pymc4#50]
I can't seem to find the definition of `ArrayStep` in pymc4. Was this object experimental or is it supposed to be somewhere?

https://github.com/pymc-devs/pymc4/blob/master/pymc4/_hmc/hmc.py#L3

**Comment by twiecki** [comment]
I think this is WIP from @aseyboldt. The idea is to copy our samplers, rip out the pymc3/theano stuff and make it work here. But as that part is not done there are still references from pymc3.

**Comment by canyon289** [comment]
Thank you
