### ISSUE TITLE
Conda-forge integration with docker build

### ISSUE THREAD

**Issue by springcoil** [pymc-devs/pymc4#53]
As part of our docker build we'll need to make sure to integrate properly with conda-forge.

As ```If we eventually want to distribute on conda-forge then users will likely be using a python binary from conda-forge (https://anaconda.org/conda-forge/python/files?version=3.6.7) rather than defaults. Regardless we can sort this out later, just wanted to chime in.```  as @kyleabeauchamp said in #49

**Comment by twiecki** [comment]
Closing for now.
