### ISSUE TITLE
Reducing config boilerplate code when specifying models.

### ISSUE THREAD

**Issue by ericmjl** [pymc-devs/pymc4#57]
Following up on @junpenglao's suggestion, I decided to start converting my Bayesian analysis recipes notebook into PyMC4 code, with the hope that I could maybe explore API design and UX aspects of using PyMC4.

I was looking at the example notebooks provided by @anhhuyalex, and immediately saw in the second cell:

```python
config = tf.ConfigProto()
config.graph_options.optimizer_options.global_jit_level = (
    tf.OptimizerOptions.ON_1)
config.intra_op_parallelism_threads = 1
config.inter_op_parallelism_threads = 1
sess = tf.InteractiveSession(config=config)
```

The immediate thought that went through my mind was, "Wow, that's a lot of up-front config that an end-user has to do." The second thought that went through my mind was, "Now I'm reminded why I don't like TensorFlow, and would much rather work with Jax." 

I'm wondering how much of this we can hide from end users? Previously with Theano, not much in-notebook configuration, with the exception of, say, setting floatX. Is hiding configuration technically feasible, or not easily doable?

**Comment by eigenfoo** [comment]
Definitely feasible! However, since PyMC4's sampling backends are still under development (I don't even  think NUTS is working), it seems a bit premature to think about coding up a smooth UI right now.

**Comment by eigenfoo** [comment]
Closing now since this isn't really an actionable item for us right now.
