### ISSUE TITLE
Observed Random Variable Support

### ISSUE THREAD

**Issue by sharanry** [pymc-devs/pymc4#6]
Add observed RV support by exploring the use of  `values` attribute in `tensorflow.distributions`

**Comment by ColCarroll** [comment]
Bumping this, since it remains open.

**Comment by sharanry** [comment]
@ColCarroll I am sorry to say that I do not have the bandwidth to take this up at the moment.

**Comment by ColCarroll** [comment]
Oop -- not aimed at you! Hope you're doing well and keeping an eye on us, though! :hugs:

**Comment by brandonwillard** [comment]
Oh, we need that for `symbolic-pymc`, as well!
