### ISSUE TITLE
Auto-transform of RVs on real line

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc4#78]
In PyMC3 we automatically transformed RVs to be on the real line, as required by e.g. ADVI and HMC. TFP has strong support for various bijectors we can use here. There are two options:
1. Implement this as part of the RV, like in PyMC3
2. Implement this as part of the sampler, like in TFP

Initial discussions I think showed consensus around option 1 and I think we can just borrow from the PyMC3 implementation which I don't think caused us many problems. Especially with https://github.com/pymc-devs/pymc4/pull/70 it gives us the option to inherit from e.g. `PositiveRandomVariable` where appropriate.

**Comment by junpenglao** [comment]
Agree with option 1 as well.
The transformed kernel returns way too many layers and is pretty difficult to debug
https://twitter.com/junpenglao/status/1086942116587208704?s=20

**Comment by ericmjl** [comment]
@twiecki can you give an example for a simple distribution? I think I'm lacking some knowledge here as to why this is done in a PPL.

**Comment by twiecki** [comment]
@ericmjl Something like a half-normal or uniform introduces discontinuities in the posterior. The gradient isn't defined at those points which causes HMC trouble. It also makes the posterior very non-normal which makes ADVI unhappy. However, if instead you don't model a half-normal but log(half-normal) those problems go away. As it's pretty clear which transforms you would want to in each case (positive-only, negative-only, interval) you can just do that automatically.

**Comment by ericmjl** [comment]
Oh! I see. I was wondering how come this was an issue. Thanks for the explanation, @twiecki. 

Just so that I can check my understanding, it's basically doing a transformation on the distribution to ensure that its transformed support covers -inf to +inf (real numbers), is that correct?

Source file in pymc3 is this: https://github.com/pymc-devs/pymc3/blob/master/pymc3/distributions/transforms.py

**Comment by twiecki** [comment]
Correct.

**Comment by ericmjl** [comment]
Allow me some time to study this... if it's implemented on the basis of our current RVs, if #70 is merged, then I think I know how to tackle this...

**Comment by ericmjl** [comment]
@twiecki, looking at the organization of the pm3 distributions, transforms are primarily used for the continuous bounded distributions (i.e. >0, unit (special case of lower-upper bounded), and lower-upper bounded). 

In pm4, do you foresee needing to re-implement those three child classes, but now as a `PositiveRV`, `UnitRV` and `BoundedRV`? (I used `RV` as shorthand for `RandomVariable`.) I think it could help to apply this lightweight organization, but with more docs on why these classes exist (i.e. for organizational purposes to make it easier to assign transformations). The alternative is to go flat and manually assign the appropriate transformation to each RV in pm4.

I'm also seeing how each transform is essentially a bijector - with "forward" and "backward" implemented. There's some trickiness, but only in terms of mapping. For example, I dug in and found that tfp.bijectors.Sigmoid() is the invlogit (without the epsilons for numerical stability), so that means our LogOdds transform in pm3 can be reimplemented now in terms of a tfp Sigmoid bijector, with `forward`, `backward`, and `jacobian_det` provided for free.

**Comment by twiecki** [comment]
Yes, that's exactly what I thought.

**Comment by junpenglao** [comment]
Small side note: in pymc3 we dont have a bijector because the jacobian is one direction only.
And I also confused by forward and backward all the time 😂

**Comment by twiecki** [comment]
Also note that we use the term `bijection` in pymc3 completely different. But yes @ericmjl, we would probably need a wrapper for TFP bijectors (or not) and figure out how to apply them to the appropriate RVs like we do in pymc3.

**Comment by ericmjl** [comment]
Cool beans!

Another option I've been bantering about in my head is to essentially replace-all `tt.` with `tf.` 🤣. What are your thoughts on that? But that would mean harnessing less of the TFP infrastructure - flexibility vs. stack?

**Comment by ericmjl** [comment]
OK! I have a skeleton for this.

**Comment by majidaldo** [comment]
I'm not seeing the value-add of just a wrapper around bijector. I thought PyMC4 is committed to TFP. So why not just use TFP TransformedDistribution?

**Comment by twiecki** [comment]
@majidaldo This issue is not about implementation but just that if a user does `HalfNormal` we do need some logic to transform it. `TransformedDistribution` sounds like it could be the best way forward. If your comment is in reference to #83 I agree, just wrapping bijectors is not adding anything and we should use TFP functionality as much as possible. If you have an idea for how to go about implementing this, want to give it a go?

**Comment by twiecki** [comment]
Sorry, I saw that @ericmjl also commented with that code here which is what your comment is in response to. So yeah, I agree.

**Comment by ericmjl** [comment]
Going to see if I can get transformed distribution out today. @canyon289 and I are going to do a paircoding thing. I put up the Transform first as it was an easier thing to wrap my head around.

**Comment by junpenglao** [comment]
I will imagine the implementation to be assigning a default transformation (now a bijector), and when a bounded distribution is called, it output a transformed distribution (a TFP distribution) with a deterministic that is the inverse transformation of the transformed.

Is this makes sense?

**Comment by ericmjl** [comment]
@junpenglao yep, that makes sense - mostly!

I wanted to check my understanding a bit here.

Firstly, I have just written the following subclass:

```python
class PositiveRandomVariable(RandomVariable):
    def __init__(self, transform=log, *args, **kwargs):
        super(self, PositiveRandomVariable).__init__(transform=transform, *args, **kwargs)
```

The `log` comes from `transforms.py`:

```python
log = bijectors.Invert(bijectors.Exp)
```

Now, `RandomVariable` is also modified:

```python
class RandomVariable(WithBackendArithmetic):
    """
    Random variable base class.

    Random variables must support 1) sampling, 2) computation of the log
    probability, and 3) conversion to tensors.
    """

    _base_dist = None

    def __init__(self, name, transform=None, *args, **kwargs):
        
        # a bunch of original stuff above here

        # Automatically apply a transformation
        self._transform = transform
        if self._transform is not None:
            self._transformed_distribution = tfd.TransformedDistribution(
                distribution=self._distribution,
                bijector=self._transform
            )
        else:
            self._transformed_distribution = None
        ctx.add_variable(self)

        # more stuff below
```

This was what was in my mind. I'm not quite sure how one would "call" on a positive-bound RV, though - would you be kind enough to elaborate please?

**Comment by twiecki** [comment]
@ericmjl In PyMC3 (which I propose we mirror here) we did the following:
1. User creates HalfNormal() RV
2. We see that a transform is required
3. We add log(HalfNormal()) to the model logp
4. We add HalfNormal() as a free floating Determinstic so that it shows up in the trace, but does not influence the model logp

**Comment by junpenglao** [comment]
@ericmjl That looks good overall, I am thinking that maybe it is better to set the distribution to be the transformed distributed, since we are evaluating the logp from it and sampling from it as well.
```python
        self._distribution_original_space = self._base_dist(name=name, *args, **kwargs)
        # Automatically apply transformation.
        self._distribution = tfd.TransformedDistribution(
            distribution=self._distribution,
            bijector=transform
        )
```

**Comment by twiecki** [comment]
@junpenglao I think we actually want to do the logp on the transformed but forward sampling on the untransformed, unless I'm thinking about this wrong.

**Comment by junpenglao** [comment]
Actually, transformed distribution in TFP have both sampling method:
https://github.com/tensorflow/probability/blob/65bfd91cf6e855674da8dd9976c067f79da46e90/tensorflow_probability/python/distributions/transformed_distribution.py#L366

We can follow similar pattern.

**Comment by canyon289** [comment]
> @junpenglao I think we actually want to do the logp on the transformed but forward sampling on the untransformed, unless I'm thinking about this wrong.

I came to the same conclusion when talking to @ericmjl  as well

**Comment by twiecki** [comment]
@junpenglao Yeah but do we want to sample from the transformed dist?

**Comment by canyon289** [comment]
@junpenglao Out of curiosity what is the value of samples from the transformed distribution when we are forward sampling and not doing an inference run?

**Comment by junpenglao** [comment]
@twiecki what i meant is that we can sample from the transformed dist to get untransformed sample
@canyon289 agree that for forward sample it does not make sense to get samples from the transformed space, since it is not the one being evaluated forward anyway.

**Comment by twiecki** [comment]
@junpenglao OK,  if that's possible then that's probably even better. The method you pointed to didn't seem to me to be doing that.

**Comment by junpenglao** [comment]
Maybe it is clearer to look at https://github.com/tensorflow/probability/blob/65bfd91cf6e855674da8dd9976c067f79da46e90/tensorflow_probability/python/distributions/transformed_distribution.py#L377

You can see in the `_call_sample_n` method, it first generate samples from the pre-transformed distribution: 
https://github.com/tensorflow/probability/blob/65bfd91cf6e855674da8dd9976c067f79da46e90/tensorflow_probability/python/distributions/transformed_distribution.py#L390
then transformed it:
https://github.com/tensorflow/probability/blob/65bfd91cf6e855674da8dd9976c067f79da46e90/tensorflow_probability/python/distributions/transformed_distribution.py#L401

Also, some of the distribution in TFP are already transformed distribution (e.g., LogNormal), in those cases maybe we dont need to apply a transform again, but instead get the underlying pre-transform distribution as the unbounded version for sampling.

**Comment by twiecki** [comment]
Great!
Yeah, LogNormal we wouldn't apply a transform on, but why would we need to get the pre-transformed one? They should both be on the real-line already.

**Comment by junpenglao** [comment]
LogNormal is positive only...

**Comment by twiecki** [comment]
You're right. I think in that case we would still transform (again) it because we can't be sure that the untransformed distribution is on the real line.
