### ISSUE TITLE
Do not require passing of RV name by AST transformation

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc4#79]
PyMC3 as well as Edward and Edward2 require (or strongly encourage) passing of an additional name to each RV:
```python
with pm.Model():
     x = pm.Normal('x', mu=0, sigma=1)
```
Note that the `x` appears twice. We need to do this because we can't easily infer that the variable `x` is called `"x"` at run-time. But we do need to keep track of it and reference it later in the trace, so that's why we need the additional argument.

This is in contrast to DSL PPL systems like stan, bugs or newer julia-based PPLs which don't need that.

It's also a common stumbling block and dislike for many pymc3 users:
![image](https://user-images.githubusercontent.com/674200/52556560-38812e80-2ded-11e9-94f9-cb7ba0b28d51.png)

![image](https://user-images.githubusercontent.com/674200/52556574-420a9680-2ded-11e9-8ec3-6a470022d360.png)

I hacked together a small prototype that inspects and transforms the AST to get the information and make the name *optional* (i.e. it can still be provided by the user):
![image](https://user-images.githubusercontent.com/674200/52557484-dbd34300-2def-11e9-9e75-98def949733f.png)

This is fairly straight-forward as you can see, we just fetch the name of the variable and add it to the code that instantiates the RV. So for pymc4 everything looks identical to before, it's just a thin layer that transforms the code before it get's executed. 

This prototype matches the PyMC3 API but I think we should change it ultimately to look something like this:
```python
def create_RV():
    return pm4.Normal(mu=0, sigma=1, name='required') # name must be provided as we don't traverse into function calls, although we probably could

@pm4.model(autoname=True) # True by default?
def mymodel():
    x = pm4.Normal(mu=0, sigma=1) # replaced by AST parser to -> x = pm4.Normal(mu=0, sigma=1, name='x')
    x2 = pm4.Normal(mu=0, sigma=1, name='but_i_want_to') # name can be supplied
    y = create_RV() 
    z = [pm4.Normal(mu=0, sigma=1, name='required {}'.format(i) for i in range(5)] # name must be provided
    x = pm4.Normal(mu=0, sigma=1) # raises exception, variable already defined
```

That code focuses mostly on edge cases where we can't easily infer the name, we don't need to handle those cases (as I think they are rare).

The main initial response from developers seems to be "thou shalt not mess with the AST" but I don't think that's a good argument. It is standard and public API of Python, the code executes in the same way (i.e. break-points can still be set) and the magic that's performed is pretty small but gives a huge improvement in user experience, and that's the focus of PyMC.

**Comment by lucianopaz** [comment]
What would happen with an RV that is not assigned to a python variable name or would it be disallowed to leave RV's hanging?

For example:

```python
def create_RV():
    return pm4.Normal(mu=0, sigma=1, name='required') # name must be provided as we don't traverse into function calls, although we probably could

@pm4.model(autoname=True) # True by default?
def mymodel():
    x = pm4.Normal(mu=0, sigma=1) # replaced by AST parser to -> x = pm4.Normal(mu=0, sigma=1, name='x')
    x2 = pm4.Normal(mu=0, sigma=1, name='but_i_want_to') # name can be supplied
    y = create_RV() + pm4.Normal(mu=x, sigma=1)  # What would happen with the inlined Normal with no name?
    z = [pm4.Normal(mu=0, sigma=1, name='required {}'.format(i) for i in range(5)] # name must be provided
```

**Comment by twiecki** [comment]
@lucianopaz You would also need to supply a name manually, but I also don't think that's a common use-case.

The good thing is that we can easily identify these cases. Instantiation of an RV *always* requires a name to be present. If the AST parser couldn't fill it in, it'll be blank and raise an exception with an informative message providing an easy fix (supply a name).

**Comment by ferrine** [comment]
What happenes with nested functions? Do they always need explicit names?

**Comment by twiecki** [comment]
Either we AST those too or you need explicit names for those. For the
initial version it will definitely be the latter. But probably the former
is also not very complicated.

**Comment by canyon289** [comment]
> The main initial response from developers seems to be "thou shalt not mess with the AST" but I don't think that's a good argument. It is standard and public API of Python, the code executes in the same way (i.e. break-points can still be set) and the magic that's performed is pretty small but gives a huge improvement in user experience, and that's the focus of PyMC.

I find this statement to be pretty compelling. To your point it is documented so if the Python developer didn't want us using it I doubt they would have put the time in to create this page.
https://docs.python.org/3/library/ast.html
