### ISSUE TITLE
ENH: add DiscreteUniform

### ISSUE THREAD

**Issue by eigenfoo** [pymc-devs/pymc4#81]
#52 left out the `DiscreteUniform` distribution (it is commented out right now). I misunderstood the errors that TFP was raising, which was ironed out in https://github.com/tensorflow/probability/issues/286. All that remains is to properly implement the DiscreteUniform distribution (most of it is written, we just need to iron out the type casting).

**Comment by ericmjl** [comment]
I'll get to it in #70.

**Comment by ferrine** [comment]
Will it be supported by samples at the time of merge?

**Comment by ericmjl** [comment]
Sorry for the question, @ferrine, but do you mean, "will it support sampling by time of merge"? Or is it something else?

**Comment by ferrine** [comment]
Oh, a typo. I meant do whether we support discrete variables in pymc4 for now? As I remember, TFD does not support this by default.

I even found some relebant [issue](https://stackoverflow.com/questions/53122714/tensorflow-probability-mcmc-with-bernoulli-distribution) on SO
