### ISSUE TITLE
When to instantiate the transformed distribution?

### ISSUE THREAD

**Issue by ericmjl** [pymc-devs/pymc4#87]
This is an issue that builds off from #83.

Background: We need transformations for continuous distributions, particularly for bounded ones (e.g. uniform, half-normal). It helps with computation during inference. 

Current design: We instantiate the appropriate distribution for an RV, and then instantiate a transformed distribution, during the initialization of an RV.

The untransformed distribution is then called during forward sampling (`RV.sample()`), and the transformed distribution is called during log_probability computation (`RV.log_prob()`). I made this design choice to keep the codebase readable, so that newcomers to pm4 can read the code base and hopefully more easily grok the design of a PPL in general.

Key questions:

* What overhead is there in keeping both the original and transformed distributions around?
* Can we design a test to measure the speed and memory overheads?
* Where will the overheads occur: at instantiation, or during computation?

Rather than debate this from a theoretical perspective only, I would like to make sure that we have measurements to back up our discussion. If there's overhead anywhere, we should be able to pinpoint where it is.

cc: @canyon289 @twiecki @junpenglao

**Comment by canyon289** [comment]
Here's three proposed implementation paths

**Always instantiate transformed distributions on RV Instantiation.**
Pros: There's always a transformed distribution.
Cons: Additional overhead for RV instantiation

**Instantiate transformed dist only in InferenceContext**
Pros: Saves on overhead in contexts when people probably don't want logps
Cons: If you do want logp in forward or freeforward context its unavailable

**Only instantiate transformed dist when log_prob is called**
Pros: Transformed dist only there when its needed
Cons: Additional conditional overhead when calling log_p, from if else or try except block

**Comment by fonnesbeck** [comment]
Since transformations are only needed to make model fitting easier, it makes sense to only invoke them in that context (all else being equal).

**Comment by lucianopaz** [comment]
This issue is resolved in the coroutine model implementation. In particular in transformed_executor.py
