### ISSUE TITLE
Add shape support

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc4#91]
Currently our RVs do not accept `shape`s.

**Comment by lucianopaz** [comment]
What's the status with this now? We have the `plate` parameter that works as a `batch_shape`. `event_shape`s seem to be inferred by the tfp distributions. The only feature missing would be to be able to sample passing a requested `sample_shape`, right?

**Comment by twiecki** [comment]
You're exactly right, we're missing `sample_shape`. It's not clear to me yet if the `plate` notation should stay like it is with being essentially an alias for `batch_shape` because then what do we do with `sample_shape`. So if you have some cycles I think some deep thinking here will go a long way.

**Comment by lucianopaz** [comment]
I've been digging around this with the forward sampling API. It seems I hadn't noticed that one cannot pass a `batch_shape` argument to a tfp distribution. The batch and event shapes are inferred automatically from the distribution parameters. We use `plate` to stack many identically distributed copies of the underlying tfp distribution. That means that in the end, our distribution's shape will be `(plate, batch_shape_from_parameters, event_shape)`.

For example
`pm.Normal("x", tf.ones(3), 1, plate=5)`
would give us a `(5, 3)` batch. I think that this makes `plate` a useful argument in itself, but it's kind of confusion so it should be very well documented

**Comment by twiecki** [comment]
Interesting, so we actually do support all the different ways to handle TFP shapes. The question is if the API does the right thing intuitively.

Also looping in @jvdillon who has thought about these issues deeper than anyone else.

**Comment by lucianopaz** [comment]
I think that we are only missing the ability to use `sample_shape` without relying on auto batching through `vectorized_map`. To do so in the forward sampling context, we'll need something like TFP's `Root`

**Comment by lucianopaz** [comment]
Closed by #193
