### ISSUE TITLE
Forward sampling returning an empty dictionary  

### ISSUE THREAD

**Issue by Adarsh-kumar** [pymc-devs/pymc4#97]
I am trying a forward sampling on mixture model example from pymc4 examples, but getting an empty dict as a result.

The model is defined as -
```python
@pm.model
def mixture(n_groups, n_points):    
    centers = pm.Normal('centers', loc=tf.zeros((n_groups, 2)), scale=1)
    scales = pm.HalfNormal('scales', 0.4 * tf.ones(n_groups))
    rates = pm.Dirichlet('rates', concentration=tf.ones(n_groups))
    
    group_assignments = pm.Multinomial('group_assignments', total_count=n_points, probs=rates)
    
    for idx in range(n_groups):
        count = tf.to_int32(group_assignments[idx])
        pm.Normal(f'group_{idx}', loc=centers[idx] * tf.ones((count, 2)), scale=scales[idx])

# Now I configured the model -
model = mixture.configure(n_groups=5, n_points=10_000)
```
I checked the tensorflow graph but it's not empty. The graph node names are- 
['zeros',
 'centers/scale',
 'centers/Identity',
 'centers/Identity_1',
 'ones/shape_as_tensor',
 'ones/Const',
 'ones',
 'mul/x',
 'mul',
 'scales/scale',............]

What could be the reasons ?

**Comment by lucianopaz** [comment]
Closing as this relates to the old context based API. It would be nice to check out this example in the current coroutine API though
